services:
  deephaven:
    build: .
    container_name: deepfeeder-dh
    ports:
      - "10001:10001"   # gRPC
      - "10000:10000"   # UI
    environment:
      PYTHONPATH: /data/app.d
      START_OPTS: >-
        -Xms1g 
        -Xmx2g 
        -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler 
        -Ddeephaven.application.dir=/data/app.d 
        -Ddeephaven.application.enabled=true
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - eagle_nest

  feeder_client:
    build:
      context: ./feeder_client
      dockerfile: Dockerfile
    container_name: feeder-client
    depends_on:
      - deephaven
    restart: unless-stopped
    networks:
      - eagle_nest

networks:
  eagle_nest:
    external: true
