[project]
name = "deepfeeder"
version = "0.1.0"
description = "DeepFeeder is a real-time market data feeder framework built on Deephaven"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "websocket-client>=1.8.0",
    "pandas>=2.2.2",
    "pyarrow>=16.1.0",
    "pydeephaven>=0.32.0"
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.5",
    "ruff>=0.11.8",
    "mypy>=1.5.1"
]

[tool.ruff]
exclude = ["build", "dist", ".venv", "runs", "research"]
line-length = 120
fix = false

[tool.ruff.lint]
select = ["E", "F", "W", "C", "B"]
ignore = ["F401", "F403", "C901", "E402"]


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-p", "no:pytest-pycache"]
python_files = ["test_*.py", "*_test.py", "tests_*.py", "*_tests.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
filterwarnings = ["ignore::DeprecationWarning"]